### ISSUE TITLE
单独尘白启动器找engine.ini 漏了个路径

### ISSUE THREAD

**Issue by Sky-And-Ground** [TeapotMoe/SnowbreakBox#1]
![image](https://github.com/user-attachments/assets/4e4c538b-4280-44a4-9a06-912eeca5c97a)
上面贴吧老哥的路径里面 data 和 Saved 中间有个 game，因此考虑补个 MainWindow.xaml.cs 37行里面补个 game

**Comment by TeapotMoe** [comment]
我测试的时候发现 Saved 文件夹在 data 目录下，便删除了 game，看来 Saved 目录位置比较薛定谔，不如两个地方都检查。

**Comment by Sky-And-Ground** [comment]
可以，这样就比较保险了

**Comment by TeapotMoe** [comment]
深入调查了一下，西山居启动器 v1.7.6 和更旧的版本没有 game 中间目录，v1.7.7 已修复。但 v1.7.7 存在新的 bug，如果目录存在空格会被截断，比如如果游戏安装在 C:\Program Files\Snow，存档会被保存在 C:\Program\Saved（大问题）。

西山居启动器 v1.7.6

| 游戏路径 | 存档路径 |
|--------|--------|
| C:\SeasunCBJQos\Game\cbjq | C:\SeasunCBJQos\Game\cbjq\Saved |
| C:\test\cbjq | C:\test\cbjq\Saved |
| C:\test test\cbjq | C:\test test\cbjq\Saved |
| C:\Program Files\Snow\data | C:\Program Files\Snow\data\Saved |

西山居启动器 v1.7.7

| 游戏路径 | 存档路径 |
|--------|--------|
| C:\SeasunCBJQos\Game\cbjq | C:\SeasunCBJQos\Game\cbjq\game\Saved |
| C:\test\cbjq | C:\test\cbjq\game\Saved |
| C:\test test\cbjq | C:\test\Saved |
| C:\Program Files\Snow\data | C:\Program\Saved |

经典启动器

| 游戏路径 | 存档路径 |
|--------|--------|
| C:\Program Files\Snow\data | %LocalAppData%\Game\Saved |
| C:\test | C:\test\game\Saved |
| C:\test test | %LocalAppData%\Game\Saved |

**Comment by Sky-And-Ground** [comment]
> 深入调查了一下，西山居启动器 v1.7.6 和更旧的版本没有 game 中间目录，v1.7.7 已修复。但 v1.7.7 存在新的 bug，如果目录存在空格会被截断，比如如果游戏安装在 C:\Program Files\Snow，存档会被保存在 C:\Program\Saved（大问题）。
> 
> 西山居启动器 v1.7.6
> 
> 游戏路径	存档路径
> C:\SeasunCBJQos\Game\cbjq	C:\SeasunCBJQos\Game\cbjq\Saved
> C:\test\cbjq	C:\test\cbjq\Saved
> C:\test test\cbjq	C:\test test\cbjq\Saved
> C:\Program Files\Snow\data	C:\Program Files\Snow\data\Saved
> 西山居启动器 v1.7.7
> 
> 游戏路径	存档路径
> C:\SeasunCBJQos\Game\cbjq	C:\SeasunCBJQos\Game\cbjq\game\Saved
> C:\test\cbjq	C:\test\cbjq\game\Saved
> C:\test test\cbjq	C:\test\Saved
> C:\Program Files\Snow\data	C:\Program\Saved
> 经典启动器
> 
> 游戏路径	存档路径
> C:\Program Files\Snow\data	%LocalAppData%\Game\Saved
> C:\test	C:\test\game\Saved
> C:\test test	%LocalAppData%\Game\Saved

空格的问题，C#本身解析会有问题吗，我印象里面记得以前命令行操作这种带空格路径是需要加上双引号的，但是代码里面我几乎从来不需要加双引号

**Comment by TeapotMoe** [comment]
取决于 API，ProcessStartInfo.Arguments 是一个字符串直接传给进程，需要自己转义，ProcessStartInfo.ArgumentList 会自动转义。西山居启动器是 qt 写的，很可能用的 C++，不管用什么，截断空格绝对属于低级错误。

**Comment by Sky-And-Ground** [comment]
既然是qt那就必定是C++了，估计应该是windows平台的经验欠缺了吧

**Comment by TeapotMoe** [comment]
光是存档路径都能整这么多花活，名副其实的草台班子😅

**Comment by Sky-And-Ground** [comment]
人手不足，核心注意力都在游戏本体上了，赶工期赶出来一些小毛病其实也能理解
